hrapps/urls.py
from django.urls import re_path

from . import views

app_name = 'hrapps'

urlpatterns = [
    re_path(r"^$", views.dashboard, name="dashboard"),
    re_path(r"^form/create/$", views.create_form, name="create_form"),
    re_path(r"^form/library/$", views.forms_library, name="forms_library"),
    re_path(r"^form/(?P<form_id>\d+)/edit/$", views.edit_form, name="edit_form"),
    re_path(r"^form/(?P<form_id>\d+)/delete/$", views.delete_form, name="delete_form"),
    re_path(r"^form/(?P<form_id>\d+)/$", views.view_form, name="view_form"),
]

hrapps/models.py
from django.db import models
from allianceauth.eveonline.models import EveCorporationInfo
from django.contrib.auth.models import User

# Create your models here.
class HRAppPerms(models.Model):
    class Meta:
        managed = False
        default_permissions = (())
        permissions = (
            ("access_hrapps", "Can access hrapps."),
            ("manage_hrapps", "Full management access."),
        )


class Form(models.Model):
    corporation = models.ForeignKey(EveCorporationInfo, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=100)
    fields = models.JSONField()
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)
    active = models.BooleanField(default=True)

    class Meta:
        default_permissions = (())
        permissions = (
            ("manage_all_forms", "Can manage forms."),
            ("create_forms", "Can create forms."),
            ("manage_corp_forms", "Can manage corp forms."),
        )

class FormResponse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    form = models.ForeignKey(Form, on_delete=models.DO_NOTHING, related_name="responses")
    response = models.JSONField()

    class Meta:
        default_permissions = (())
        permissions = (
            ("view_all_responses", "Can view responses."),
            ("create_response", "Can create responses."),
            ("view_corp_responses", "Can view corp responses."),
        )

class ResponseComment(models.Model):
    response = models.ForeignKey(FormResponse, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    content = models.TextField(null=False, blank=False)
    reply_to = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, related_name='replies')
    # Private comments and their replies should be hidden from the respondent even if they have the permissions
    # to view/create comments. (Except where user has manage_hrapps perm)
    private = models.BooleanField(default=False)

    class Meta:
        default_permissions = (())
        permissions = (
            ("create_comment", "Can comment on form responses."),       # Can create AND view
            ("view_comment", "Can view comments on form responses."),   # Can view but NOT create
        )

hrapps/views.py
import json

from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from allianceauth.services.hooks import get_extension_logger
from allianceauth.eveonline.models import EveCorporationInfo
from .models import Form

logger = get_extension_logger(__name__)


def get_or_create_corp(corporation_id):
    try:
        corp = EveCorporationInfo.objects.get(corporation_id=corporation_id)
    except EveCorporationInfo.DoesNotExist:
        EveCorporationInfo.objects.create_corporation(corporation_id)
        corp = EveCorporationInfo.objects.get(corporation_id=corporation_id)
    return corp


class Field:
    def __init__(self, type, question, options=None, required=False):
        self.type = type
        self.question = question
        self.required = required
        if options is not None:
            self.options = tuple(options)
        else:
            self.options = None


# Create your views here.
def dashboard(request):
    return render(request, "hrapps/dashboard.html")


def create_form(request):
    if request.method == "POST":
        body = request.body.decode("utf-8")
        logger.debug(body)
        body_json = json.loads(body)

        corp = get_or_create_corp(request.user.profile.main_character.corporation_id)
        form = Form(
            name=body_json["name"],
            description=body_json["description"],
            corporation=corp,
            active=body_json["active"],
            fields=body_json["questions"],
        )
        try:
            form.save()
        except Exception as e:
            logger.error(e)
            return HttpResponse(status=500)
        return HttpResponse(status=201)

    return render(request, "hrapps/builder.html", {"action": "Create"})


def edit_form(request, form_id):
    form = Form.objects.get(id=form_id)
    if request.method == "POST":
        body = request.body.decode("utf-8")
        logger.debug(body)
        body_json = json.loads(body)

        form.name = body_json["name"]
        form.description = body_json["description"]
        form.active = body_json["active"]
        form.fields = body_json["questions"]
        try:
            form.save()
        except Exception as e:
            logger.error(e)
            return HttpResponse(status=500)
        return HttpResponse(status=200)
    fields = []

    for field in form.fields:
        field = Field(**field)
        fields.append(field)

    fields = tuple(fields)
    return render(request, "hrapps/builder.html", {"action": "Edit", "form": form, "fields": fields})


def delete_form(request, form_id):
    sender = request.META.get("HTTP_REFERER", "/")

    try:
        form = Form.objects.get(id=form_id)
        if request.user.profile.main_character.corporation_id == form.corporation.corporation_id \
                or request.user.is_superuser:
            form.delete()

            messages.success(request, "Form deleted successfully.")
        else:
            messages.error(request, "You do not have permission to delete this form.")
    except Exception as e:
        logger.error(e)
        messages.error(request, "Error deleting form.")
    return redirect(sender)


def view_form(request, form_id):
    form = Form.objects.get(id=form_id)

    fields = []

    for field in form.fields:
        field = Field(**field)
        fields.append(field)

    fields = tuple(fields)
    return render(request, "hrapps/form_viewer.html", {"action": "Edit", "form": form, "fields": fields})


def forms_library(request):
    forms = Form.objects.all()
    ctx = {"forms": forms}
    return render(request, "hrapps/form_library.html", ctx)

hrapps/templates/hrapps/base.html
{% extends "allianceauth/base-bs5.html" %}

{% load i18n %}
{% load navactive %}

{% block page_title %}{% block hr_title %}{% endblock %} - HR Apps{% endblock %}

{% block header_nav_brand %}{% translate "HR Apps" %}{% endblock %}

{% block header_nav_collapse_left %}
    <li class="nav-item">
        <a
            class="nav-link {% navactive request 'hrapps:create_form' %}"
            href="{% url 'hrapps:create_form' %}"
        >
            {% translate "Create Form" %}
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% navactive request 'hrapps:forms_library' %}"
           href="{% url 'hrapps:forms_library' %}"
        >
            {% translate "Forms Library" %}
        </a>
    </li>
{% endblock %}

{% block header_nav_collapse_right %}
    {# Nothing #}
{% endblock %}

{% block content %}
    <div>
        {% block hrapps_content %}{% endblock %}
    </div>
{% endblock %}

{% block extra_css %}
    {% block more_css %}{%endblock%}
{% endblock extra_css %}

hrapps/templates/hrapps/builder.html
{% extends 'hrapps/base.html' %}

{% block hr_title %}{{ action|title }} Form{% endblock %}

{%  block more_css %}
    {% include 'hrapps/bundles/coreuifree-css.html' %}
    {% include 'hrapps/bundles/materialdesignicons-css.html' %}
    {% include 'hrapps/bundles/builder-css.html' %}
{% endblock %}

{% block hrapps_content %}
    {% include "hrapps/partials/builder_templates.html" %}
    {% include "hrapps/partials/builder_success_modal.html" %}
    <div class="row">
        <h3>Form Builder</h3>
    </div>
    <div class="row mb-2">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Form Information
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="name">Form Name</label>
                        <input type="text" class="form-control" id="name" value="{{ form.name }}" required>
                        <div class="invalid-feedback">
                            A form name is required.
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="description">Form Description</label>
                        <textarea class="form-control" id="description" rows="3">{{ form.description }}</textarea>
                    </div>
                    <div class="form-group" style="display: flex; justify-content: flex-end;">
                        <input type="checkbox" class="form-check-input" id="active" style="margin-right: 3px;" {% if active %} checked {% endif %}>
                        <label for="active">Active</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="sticky-offset">
                <div class="card">
                    <div class="card-header">
                        Field Toolbox
                    </div>
                    <div class="card-body">
                        <div id="text-field" draggable="true" class="card card-body bg-secondary form-tool">
                            <p class="form-tool"><span class="mdi mdi-form-textbox icon-xl"></span> Text Box</p>
                        </div>
                        <div id="text-area" draggable="true" class="card card-body bg-secondary form-tool">
                            <p class="form-tool">
                                <span class="cil-short-text icon-xl" style="vertical-align: text-bottom"></span>
                                Text Area (Multi-Line Text)
                            </p>
                        </div>
                        <div id="dropdown" draggable="true" class="card card-body bg-secondary form-tool">
                            <p class="form-tool"><span class="mdi mdi-form-dropdown icon-xl"></span> Dropdown</p>
                        </div>
                        <div id="checkboxes" draggable="true" class="card card-body bg-secondary form-tool">
                            <p class="form-tool">
                                <span class="mdi mdi-format-list-checkbox icon-xl"></span>
                                Checkboxes
                            </p>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary mt-2" onclick="submitForm('{{ csrf_token }}')">{{ action|title }} Form</button>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Form Designer
                </div>
                <div id="designer" class="card-body">
                    <div id="dropField" class="{% if action|lower == "edit" %}invisible hidden {% else %}visible {% endif %}" style="z-index: -1;">
                        <div class="card dropzone">
                            <H1>Drag and Drop Fields Here</H1>
                        </div>
                    </div>
                {% if action|lower == "edit" %}
                    {% for field in fields %}
                        {% with "hrapps/partials/fields/builder/"|add:field.type|add:".html" as field_partial %}
                            {% include field_partial with field=field id=forloop.counter %}
                        {% endwith %}
                    {% endfor %}
                {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include "hrapps/bundles/builder-js.html" %}
    <script type="text/javascript">
        {% if action|lower == "edit" %}
            const qs = getQuestions();

            for (let i = 0; i < qs.length; i++) {
                qs[i].addEventListener("dragstart", dragstartHandler);
            }
        {% endif %}

        const fieldTools = document.querySelectorAll("div.form-tool");

        for (let i = 0; i < fieldTools.length; i++) {
            fieldTools[i].addEventListener("dragstart", dragstartHandler);
            fieldTools[i].addEventListener("dblclick", dblclickHandler);
        }

        designer.addEventListener("dragover", (event) => {
            event.preventDefault();
        })
        designer.addEventListener("drop", designerDropHandler);
    </script>
{% endblock %}

hrapps/templates/hrapps/bundles/builder-css.html
{% load sri %}

{% sri_static "hrapps/css/builder.css" %}

hrapps/templates/hrapps/bundles/builder-js.html
{% load sri %}

{% sri_static "hrapps/js/builder.js" %}

hrapps/templates/hrapps/bundles/coreuifree-css.html
{% load sri %}

{% sri_static "hrapps/css/coreuifree.min.css" %}

hrapps/templates/hrapps/bundles/materialdesignicons-css.html
{% load sri %}

{% sri_static "hrapps/css/materialdesignicons.min.css" %}

hrapps/templates/hrapps/dashboard.html
{% extends "hrapps/base.html" %}

{% block hrapps_content %}
    <p>Something</p>
{% endblock %}

hrapps/templates/hrapps/form_library.html
{% extends "hrapps/base.html" %}

{% load evelinks %}
{% load i18n %}

{% block hr_title %}Forms Library{% endblock %}

{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock %}

{% block hrapps_content %}
    {% include "hrapps/partials/delete_confirm_modal.html" %}
    <div class="card">
        <div class="card-header">
            Forms Library
        </div>
        <div class="card-body">
            {% if not forms %}
                <div class="alert alert-warning text-center" role="alert">{% translate "No Forms Found" %}</div>
            {% else %}
                <table class="table table-striped table-hover" id="forms_table">
                    <thead>
                        <tr>
                            <th>{% translate "Form Name" %}</th>
                            <th>{% translate "Description" %}</th>
                            <th>{% translate "Created" %}</th>
                            <th>{% translate "Updated" %}</th>
                            <th>{% translate "Active" %}</th>
                            <th>{% translate "Corporation" %}</th>
                            <th>{% translate "Utilities" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for form in forms %}
                            <tr>
                                <td>{{ form.name }}</td>
                                <td>{{ form.description }}</td>
                                <td>{{ form.created }}</td>
                                <td>{% if updated %}{{ form.updated }}{% else %}-{% endif %}</td>
                                <td>
                                    {% if form.active %}
                                        <span class="fa fa-check-circle" style="color: var(--bs-success)"></span>
                                    {% else %}
                                        <span class="fa fa-times-circle" style="color: var(--bs-danger)"></span>
                                    {% endif %}
                                </td>
                                <td>
                                    <img src="{{ form.corporation|corporation_logo_url:64 }}"
                                         alt="{{ form.corporation.corporation_name }} Logo">
                                    {{ form.corporation.corporation_name }}
                                </td>
                                <td>
                                    <a href="{% url 'hrapps:edit_form' form.id %}" class="btn btn-sm btn-warning">
                                        <span class="fa fa-edit"></span>
                                    </a>
                                    <button
                                            data-delete-url="{% url 'hrapps:delete_form' form.id %}"
                                            class="btn btn-sm btn-danger"
                                            onClick="showDeleteConfirmModal(this)"
                                    >
                                        <span class="fa fa-times"></span>
                                    </button>
                                    <a href="{% url 'hrapps:view_form' form.id %}" class="btn btn-sm btn-info">
                                        <span class="fa fa-eye"></span>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}

    {% get_datatables_language_static LANGUAGE_CODE as DT_LANG_PATH %}

    <script>
        $(document).ready(function () {
            $('#forms_table').DataTable({
                language: {url: '{{ DT_LANG_PATH }}'}
            });
        })

        function showDeleteConfirmModal(elem) {
            const deleteUrl = elem.dataset.deleteUrl;
            const deleteModal = document.getElementById("delete-modal");
            const deleteBtn = document.getElementById("delete-btn");
            deleteBtn.href = deleteUrl;
            const modal = new bootstrap.Modal(deleteModal);
            modal.show();
        }
    </script>
{% endblock %}

hrapps/templates/hrapps/form_viewer.html
{% extends "hrapps/base.html" %}

{% load i18n %}
{% load evelinks %}

{% block hrapps_content %}
<div class="row">
    <h3>{{ form.name }}</h3>
    <h4><img src="{{ form.corporation|corporation_logo_url:32 }}" alt="{{ form.corporation.corporation_name }} Logo"> <small class="text-body-secondary">{{ form.corporation.corporation_name }}</small></h4>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="card">
            <div class="card-header">{%  translate "Form Details" %}</div>
            <div class="card-body">
                <dl>
                    <dt>{% translate "Form Description" %}</dt>
                    <dd>{{ form.description }}</dd>
                </dl>
                <dl>
                    <dt>{% translate "Created" %}</dt>
                    <dd>
                        {% if LANGUAGE_CODE == 'ko' or LANGUAGE_CODE == 'ja' %}
                            {{ form.created|date:'Y-m-d / H:i:s' }}
                        {% else %}
                            {{ form.created|date:'d M Y H:i:s' }}
                        {% endif %}
                    </dd>
                </dl>
                {% if form.updated %}
                    <dl>
                        <dt>{% translate "Updated" %}</dt>
                        <dd>
                            {% if LANGUAGE_CODE == 'ko' or LANGUAGE_CODE == 'ja' %}
                                {{ form.updated|date:'Y-m-d / H:i:s' }}
                            {% else %}
                                {{ form.updated|date:'d M Y H:i:s' }}
                            {% endif %}
                        </dd>
                    </dl>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">{% translate "Form Preview" %}</div>
            <div class="card-body">
                {% for field in fields %}
                    {% with "hrapps/partials/fields/form/"|add:field.type|add:".html" as field_partial %}
                        {% include field_partial with field=field disabled=True id=forloop.counter %}
                    {% endwith %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

hrapps/templates/hrapps/partials/builder_success_modal.html
<div class="modal fade" id="success-modal" tabindex="-1" aria-hidden="true" data-bs-backdrop="static"
     style="
     --bs-modal-header-border-color: '';
     --bs-modal-footer-border-color: '';
     --bs-modal-border-color: '';
     color: white;"
>
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content bg-success" style="box-shadow: 0 0 20px rgba(25, 135, 84, 0.6);">
            <div class="modal-header">
                <h4 class="modal-title"><span class="fa fa-check-circle"></span> Success!</h4>
            </div>
            <div class="modal-body">
                    <p id="success-message"></p>
            </div>
            <div class="modal-footer justify-content-between">
                <p>You will be redirected back to the dashboard in <span id="countdown"></span> seconds.</p>
                <small style="font-size: x-small">
                    If you are not redirected, click <a href="{% url 'hrapps:dashboard' %}" style="color: white">here</a>.
                </small>
            </div>
        </div>
    </div>
</div>

hrapps/templates/hrapps/partials/builder_templates.html
<template id="text-field-template">
    {% include "hrapps/partials/fields/builder/text-field.html" %}
</template>

<template id="text-area-template">
    {% include "hrapps/partials/fields/builder/text-area.html" %}
</template>

<template id="dropdown-template">
    {% include "hrapps/partials/fields/builder/dropdown.html" %}
</template>

<template id="checkboxes-template">
    {% include "hrapps/partials/fields/builder/checkboxes.html" %}
</template>

<template id="list-group-item-template">
    {% include "hrapps/partials/fields/builder/list-group-item.html" %}
</template>

hrapps/templates/hrapps/partials/delete_confirm_modal.html
<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger">
                <h6 class="modal-title" id="deleteModalLabel">Delete Form</h6>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this form?</p>
                <div class="text-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="" class="btn btn-danger" id="delete-btn">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>

hrapps/templates/hrapps/partials/fields/builder/checkboxes.html
    <div class="card bg-secondary" style="margin-bottom: 3px;" draggable="true" data-field="checkboxes" {% if id %}id="question_{{ id }}"{% endif %}>
        <div class="card-header">
            <div class="card-title mb-0">
                Checkboxes
                <button type="button" class="btn btn-xs btn-danger float-end ms-1" onClick="removeField(this.closest('.card'))">
                    <span class="fa fa-times"></span>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="form-group">
                        <label class="form-label" for="question">Question</label>
                        <input type="text" class="form-control" id="question" value="{{ field.question }}" required>
                        <div class="invalid-feedback">
                            This field is required. Please click the delete button to remove this field.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group" style="display: flex; justify-content: flex-end;">
                        <input type="checkbox" class="form-check-input" id="required" style="margin-right: 3px;" {% if field.required %}checked{% endif %}>
                        <label class="form-label" for="required">Required?</label>
                    </div>
                </div>
                    <div class="card" id="options_card">
                        <div class="card-header">
                            <div class="card-title mb-0">
                                Options
                                <button class="btn btn-xs bg-success float-end ms-1" onclick="addOption(this.closest('.card'))">
                                    <span class="fa fa-plus"></span> Add Option
                                </button>
                            </div>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% if field.options %}
                                {% for option in field.options %}
                                    {% include "hrapps/partials/fields/list-group-item.html" with option=option id=forloop.counter %}
                                {% endfor %}
                            {% endif %}
                        </ul>
                        <div class="card-footer">
                            <span class="fa fa-circle-info"></span> Note: A checkbox field must have a minimum of 2 options.
                        </div>
                    </div>
            </div>
        </div>
    </div>

hrapps/templates/hrapps/partials/fields/builder/dropdown.html
<div class="card bg-secondary" style="margin-bottom: 3px;" draggable="true" data-field="dropdown" {% if id %}id="question_{{ id }}"{% endif %}>
        <div class="card-header">
            <div class="card-title mb-0">
                Dropdown
                <button type="button" class="btn btn-xs btn-danger float-end ms-1" onClick="removeField(this.closest('.card'))">
                    <span class="fa fa-times"></span>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="form-group">
                        <label class="form-label" for="question">Question</label>
                        <input type="text" class="form-control" id="question" value="{{ field.question }}" required>
                        <div class="invalid-feedback">
                            This field is required. Please click the delete button to remove this field.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group" style="display: flex; justify-content: flex-end;">
                        <input type="checkbox" class="form-check-input" id="required" style="margin-right: 3px;" {% if field.required %}checked{% endif %}>
                        <label class="form-label" for="required">Required?</label>
                    </div>
                </div>
                    <div class="card" id="options_card">
                        <div class="card-header">
                            <div class="card-title mb-0">
                                Options
                                <button class="btn btn-xs bg-success float-end ms-1" onclick="addOption(this.closest('.card'))">
                                    <span class="fa fa-plus"></span> Add Option
                                </button>
                            </div>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% if field.options %}
                                {% for option in field.options %}
                                    {% include "hrapps/partials/fields/list-group-item.html" with option=option id=forloop.counter %}
                                {% endfor %}
                            {% endif %}
                        </ul>
                        <div class="card-footer">
                            <span class="fa fa-circle-info"></span> Note: A dropdown must have a minimum of 2 options.
                        </div>
                    </div>
            </div>
        </div>
    </div>

hrapps/templates/hrapps/partials/fields/builder/list-group-item.html
<li class="list-group-item" {% if id %}id="option_{{ id }}"{% endif %}>
    <div class="d-flex">
        <input type="text" class="form-control" id="option" value="{{ option }}" required>
        <btn class="btn btn-danger ms-2" title="Delete Option" onclick="removeField(this.closest('.list-group-item'))">
            <span class="fa fa-trash"></span>
        </btn>
    </div>
    <div class="invalid-feedback">
        This field cannot be empty. Click the delete button to remove this option.
    </div>
</li>

hrapps/templates/hrapps/partials/fields/builder/text-area.html
<div class="card bg-secondary" style="margin-bottom: 3px;" draggable="true" data-field="text-area" {% if id %}id="question_{{ id }}"{% endif %}>
        <div class="card-header">
            <div class="card-title mb-0">
                Text Area (Multi-Line Text)
                <button type="button" class="btn btn-xs btn-danger float-end ms-1" onClick="removeField(this.closest('.card'))">
                    <span class="fa fa-times"></span>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="form-group">
                        <label class="form-label" for="question">Question</label>
                        <input type="text" class="form-control" id="question" value="{{ field.question }}" required>
                        <div class="invalid-feedback">
                            This field is required. Please click the delete button to remove this field.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group" style="display: flex; justify-content: flex-end;">
                        <input type="checkbox" class="form-check-input" id="required" style="margin-right: 3px;" {% if field.required %}checked{% endif %}>
                        <label class="form-label" for="required">Required?</label>
                    </div>
                </div>
            </div>
        </div>
    </div>

hrapps/templates/hrapps/partials/fields/form/checkboxes.html
<div class="form-field checkbox-field" data-required="{{ field.required }}">
    <h5>{{ field.question }} {% if field.required %}<span style="color: red">*</span>{% endif %}</h5>
    {% for option in field.options %}
        <div class="form-check">
            <input
                    class="form-check-input"
                    type="checkbox"
                    value="{{ option }}"
                    id="question_{{ id }}_option_{{ forloop.counter }}"
                    {% if disabled %} disabled {% endif %}
            >
            <label class="form-check-label" for="question_{{ id }}_option_{{ forloop.counter }}">{{ option }}</label>
        </div>
    {% endfor %}
</div>